default_language_version:
  python: python3.8
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--settings-path, pyproject.toml]
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        alias: ruff-lint
        args: [--config, pyproject.toml]
        stages: [manual]
      - id: ruff-format
        alias: ruff
        args: [--config, pyproject.toml]
        stages: [pre-commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
