[tool.isort]
force_alphabetical_sort_within_sections = true
from_first = false
line_length = 100
lines_between_sections = 0
lines_between_types = 1
profile = "black"
py_version = 38

[tool.ruff]
line-length = 100
target-version = "py38"
