echo "${yellow}Starting siyavula_api_python_pyramid${reset}"
echo "${green}Routes:${reset}"
echo -e "${green}\tAnonymous Activity: ${reset}${blue}http://localhost:6543/anonymous${reset}"
echo -e "${green}\tStandalone Activity: ${reset}${blue}http://localhost:6543/standalone${reset}"
echo -e "${green}\tStandalone List Activity: ${reset}${blue}http://localhost:6543/standalone-list${reset}"
echo -e "${green}\tAssignment Activity: ${reset}${blue}http://localhost:6543/assignment${reset}"
echo -e "${green}\tPractice Activity: ${reset}${blue}http://localhost:6543/practice${reset}"
echo -e "${green}\tGet Activity: ${reset}${blue}http://localhost:6543/get-activity${reset}"
echo -e "${green}\tTable of Contents: ${reset}${blue}http://localhost:6543/toc${reset}"
echo -e "${green}\tPractice Activity Table of Contents (Mastery Applied): ${reset}${blue}http://localhost:6543/toc-mastery${reset}"
echo -e "${green}\tResponse Data: ${reset}${blue}http://localhost:6543/response-data${reset}"
echo -e "${green}\tUser Link Token: ${reset}${blue}http://localhost:6543/user-link-token${reset}"
