name: Dependabot issue for PRs
on:
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  issues: write
  repository-projects: write
  pull-requests: write

jobs:
  issue:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Manage Dependabot Issues
        uses: Siyavula/github_actions/actions/dependabot_issue_manager@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
